/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vsystem;

import static java.awt.event.KeyEvent.VK_ENTER;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static vsystem.adminDashboard.cd1;
import static vsystem.adminDashboard.cd2;
import static vsystem.adminDashboard.cd3;
import static vsystem.adminDashboard.cd4;
import static vsystem.adminDashboard.cd5;
import static vsystem.adminDashboard.cd6;
import static vsystem.adminDashboard.change;
import vsystem.adminDashboard.*;
import static vsystem.adminDashboard.resetColor;
/**
 *
 * @author Raven
 */
public class addPartylist extends javax.swing.JFrame {

    public ImageIcon back,homebg;
    public addPartylist() {
        initComponents();
        setLocationRelativeTo(null);
                back = new ImageIcon("src\\icons\\back.jpg");
                backg4.setIcon(back);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        backg4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Partylist Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        name1.setBackground(new java.awt.Color(36, 47, 65));
        name1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 255, 255));
        name1.setBorder(null);
        name1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                name1KeyPressed(evt);
            }
        });
        jPanel1.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 72, 227, 30));

        jButton1.setBackground(new java.awt.Color(36, 47, 65));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 147, 45));
        jPanel1.add(backg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 410, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 88, 400, 250));

        jPanel2.setBackground(new java.awt.Color(23, 35, 51));

        jButton3.setBackground(new java.awt.Color(36, 47, 65));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Back");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADD PARTYLIST");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
        try {
            addpartylist();
        } catch (IOException ex) {
            Logger.getLogger(addPartylist.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void name1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name1KeyPressed
       if(evt.getKeyCode()==VK_ENTER){
           try { 
               addpartylist();
           } catch (IOException ex) {
               Logger.getLogger(addPartylist.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
    }//GEN-LAST:event_name1KeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        new adminDashboard().setVisible(true);
       methodd();
    }//GEN-LAST:event_jButton3ActionPerformed
public void methodd(){
     change.setText("CANDIDATE PROFILE");
      adminDashboard. setColor( adminDashboard.btn_3);
      adminDashboard.   ind_3.setOpaque(true);
        resetColor(new JPanel[]{adminDashboard.btn_1,  adminDashboard.btn_8, adminDashboard.btn_12,adminDashboard.btn_9,adminDashboard.btn_4},
                new JPanel[]{adminDashboard.ind_1,  adminDashboard.ind_12, adminDashboard.ind_8, adminDashboard.ind_12,adminDashboard.ind_9,adminDashboard.ind_4});
        cd2.setVisible(true);
        cd1.setVisible(false);
        cd3.setVisible(false);
        cd4.setVisible(false);
        cd5.setVisible(false);
        cd6.setVisible(false);
        adminDashboard. edit1.setVisible(false);
          adminDashboard.  fullname.setVisible(false);
          adminDashboard.  confirmedit.setVisible(false);
          adminDashboard.  add.setVisible(true);
         adminDashboard.   delete.setVisible(false);
          adminDashboard.  jButton2.setVisible(true);   
          adminDashboard.  FN.setText("");
         adminDashboard.   LN.setText("");
          adminDashboard.  female.setSelected(false);
         adminDashboard.     male.setSelected(false);
         adminDashboard.    department.setSelectedIndex(0);
         adminDashboard.   position.setSelectedIndex(0);
          adminDashboard.  partylist.setSelectedIndex(0);
           adminDashboard. addedit.setText("Add");
}
    public void addpartylist() throws IOException{
       if(name1.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(null,"Enter Field");
       }else{
        String partylist;
        partylist=name1.getText().trim();
        BufferedWriter sf;
                    sf = new BufferedWriter(new FileWriter("src\\textFile\\partylist",true));
                    sf.append(partylist+"\n");
                    sf.close();
                  
                    JOptionPane.showMessageDialog(null, "Added");
                  dispose();
                  adminDashboard x = new adminDashboard();
                  x.setVisible(true);
                   methodd();
       }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addPartylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addPartylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addPartylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addPartylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addPartylist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backg4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name1;
    // End of variables declaration//GEN-END:variables
}
