/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vsystem;

import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Raven
 */
public class login extends javax.swing.JFrame {
    public ImageIcon icn1,icn2,backg,logoe,exit1;
public static String linezz = "", id = "";
    public login() {
        initComponents();
         setLocationRelativeTo(null);
         icn1=new ImageIcon("src\\icons\\visible.png");
         icn2=new ImageIcon("src\\icons\\invisible.png");
         backg=new ImageIcon("src\\icons\\back.jpg");
         logoe=new ImageIcon("src\\icons\\uic-logo2.png");
         exit1=new ImageIcon("src\\icons\\close.png");
         back.setIcon(backg);
         logo.setIcon(logoe);
         icon1.setIcon(icn1); 
         icon2.setIcon(icn2);
         close.setIcon(exit1);
        icon2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        unameTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        unamelabel = new javax.swing.JLabel();
        passlabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(0, 0));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Username:");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Password:");

        pass.setBackground(new java.awt.Color(36, 47, 65));
        pass.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setCaretColor(new java.awt.Color(36, 47, 65));
        pass.setMinimumSize(new java.awt.Dimension(14, 24));
        pass.setPreferredSize(new java.awt.Dimension(14, 23));
        pass.setSelectedTextColor(new java.awt.Color(36, 47, 65));
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passKeyPressed(evt);
            }
        });

        unameTF.setBackground(new java.awt.Color(36, 47, 65));
        unameTF.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        unameTF.setForeground(new java.awt.Color(255, 255, 255));
        unameTF.setCaretColor(new java.awt.Color(36, 47, 65));
        unameTF.setPreferredSize(new java.awt.Dimension(14, 23));
        unameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameTFActionPerformed(evt);
            }
        });
        unameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                unameTFKeyPressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(36, 47, 65));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(36, 47, 65));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(36, 47, 65));
        jLabel3.setText("Register here!");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        unamelabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        unamelabel.setForeground(new java.awt.Color(214, 14, 14));
        unamelabel.setText(" ");

        passlabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        passlabel.setForeground(new java.awt.Color(214, 14, 14));
        passlabel.setText(" ");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Login or Register");

        jLabel11.setForeground(new java.awt.Color(36, 47, 65));
        jLabel11.setText("_________________");

        close.setText(" ");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon1MouseClicked(evt);
            }
        });

        icon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3))))
                    .addComponent(jLabel1)
                    .addComponent(jLabel10)
                    .addComponent(unameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel10)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unamelabel)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passlabel)
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pass.getAccessibleContext().setAccessibleName("");

        jPanel3.setPreferredSize(new java.awt.Dimension(550, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SY: 2019-2020");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("COMMISION ON ELECTION");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 551, 230, 30));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("AND APPOINTMENTS");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 591, -1, -1));
        jPanel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 340, 350));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SSG ELECTION");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 540, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void checkerr() {

        if (unameTF.getText().trim().isEmpty() && pass.getText().trim().isEmpty()) {
            unamelabel.setText("Enter All Fields");
            passlabel.setText("Enter All Fields");
        } else if (unameTF.getText().trim().isEmpty()) {
            unamelabel.setText("Username is Empty");
            passlabel.setText(" ");
        } else if (pass.getText().trim().isEmpty()) {
            unamelabel.setText(" ");
            passlabel.setText("Password is Empty");
        } else {
            String uname, pswd, line, line2, username, password, status, departss, confirm;
            int unamechecker = 0;
            uname = unameTF.getText().trim();//geting text in jtextfield
            pswd = pass.getText().trim();//geting text in jpasswordfield
            try {
                Scanner sc = new Scanner(new FileReader("src\\textFile\\logintxt"));//reading text file
                while (sc.hasNextLine()) { //logic
                    line = sc.nextLine();
                    if (line.equals("")) {
                        continue;
                    }
                    Scanner lineinput = new Scanner(line);
                    username = lineinput.next();
                    password = lineinput.next();
                    status = lineinput.next();
                    confirm = lineinput.next();
                    if (uname.equals(username)) {
                        unamechecker = 1;
                        if (pswd.equals(password)) {
                            if (confirm.equals("Verified")) { // confirms verification
                                if (status.equals("user")) //user status
                                {
                                    Scanner sc1 = new Scanner(new FileReader("src\\textFile\\users"));//reading text file
                                    while (sc1.hasNextLine()) { //logic
                                        line2 = sc1.nextLine();
                                        if (line2.equals("")) {
                                            continue;
                                        }
                                        Scanner lineinput2 = new Scanner(line2);
                                        String iddd = lineinput2.next();
                                        String firstnameuser = lineinput2.next();
                                        String surnameuser = lineinput2.next();
                                        String usercourse = lineinput2.next();
                                        String genderzz = lineinput2.next();
                                        String valid = lineinput2.next();
                                        if (iddd.equals(username)) //checking id to otherfile
                                        {
                                            if (valid.equals("NOTYETVOTED")) {
                                                //checking course
                                                if (usercourse.equals("CTE")) {
                                                    String k = firstnameuser + " " + surnameuser;
                                                    linezz = "CTE";
                                                    id = k;
                                                    setVisible(false);//to hide the windoww
                                                    dispose();//to close the window without stoping the app
                                                    userpromt x = new userpromt();//calling other jframe
                                                    x.setVisible(true);
                                                }
                                                if (usercourse.equals("CEA")) {
                                                    String k = firstnameuser + " " + surnameuser;
                                                    linezz = "CEA";
                                                    id = k;
                                                    setVisible(false);//to hide the windoww
                                                    dispose();//to close the window without stoping the app
                                                    userpromt x = new userpromt();//calling other jframe
                                                    x.setVisible(true);
                                                }
                                                if (usercourse.equals("CABE")) {
                                                    String k = firstnameuser + " " + surnameuser;
                                                    linezz = "CABE";
                                                    id = k;
                                                    setVisible(false);//to hide the windoww
                                                    dispose();//to close the window without stoping the app
                                                    userpromt x = new userpromt();//calling other jframe
                                                    x.setVisible(true);
                                                }
                                                if (usercourse.equals("CCS")) {
                                                    String k = firstnameuser + " " + surnameuser;
                                                    linezz = "CCS";
                                                    id = k;
                                                    setVisible(false);//to hide the windoww
                                                    dispose();//to close the window without stoping the app
                                                    userpromt x = new userpromt();//calling other jframe
                                                    x.setVisible(true);
                                                }
                                                if (usercourse.equals("CAH")) {
                                                    String k = firstnameuser + " " + surnameuser;
                                                    linezz = "CAH";
                                                    id = k;
                                                    setVisible(false);//to hide the windoww
                                                    dispose();//to close the window without stoping the app
                                                    userpromt x = new userpromt();//calling other jframe
                                                    x.setVisible(true);
                                                }
                                                if (usercourse.equals("CMBS")) {
                                                    String k = firstnameuser + " " + surnameuser;
                                                    linezz = "CMBS";
                                                    id = k;
                                                    setVisible(false);//to hide the windoww
                                                    dispose();//to close the window without stoping the app
                                                    userpromt x = new userpromt();//calling other jframe
                                                    x.setVisible(true);
                                                }
                                                if (usercourse.equals("MUSIC")) {
                                                    String k = firstnameuser + " " + surnameuser;
                                                    linezz = "MUSIC";
                                                    id = k;
                                                    setVisible(false);//to hide the windoww
                                                    dispose();//to close the window without stoping the app
                                                    new userpromt().setVisible(true);//calling other jframe
                                                }
                                                if (usercourse.equals("NURSING")) {
                                                    String k = firstnameuser + " " + surnameuser;
                                                    linezz = "NURSING";
                                                    id = k;
                                                    setVisible(false);//to hide the windoww
                                                    dispose();//to close the window without stoping the app
                                                    new userpromt().setVisible(true);//calling other jframe
                                                }
                                                if (usercourse.equals("CHEFS")) {
                                                    String k = firstnameuser + " " + surnameuser;
                                                    linezz = "CHEFS";
                                                    id = k;
                                                    setVisible(false);//to hide the windoww
                                                    dispose();//to close the window without stoping the app
                                                    new userpromt().setVisible(true);//calling other jframe
                                                }
                                                if (usercourse.equals("CPC")) {
                                                    String k = firstnameuser + " " + surnameuser;
                                                    linezz = "CPC";
                                                    id = k;
                                                    setVisible(false);//to hide the windoww
                                                    dispose();//to close the window without stoping the app
                                                    new userpromt().setVisible(true);//calling other jframe
                                                }
                                            }
                                            if (valid.equals("VOTED")) {
                                                dispose();
                                                new voted().setVisible(true);

                                            }
                                        }
                                    }
                                }
                            }
                            if (confirm.equals("NotVerified")) {  // confirms verification
                                JOptionPane.showMessageDialog(null, "Account Not Verified");
                            }

                            if (uname.equals("admin")) //admin status
                            {
                                setVisible(false);//to hide the windoww
                                dispose();//to close the window without stoping the app
                                new adminDashboard().setVisible(true); //calling other jframe

                            }

                        } else {
                            unamelabel.setText(" ");
                            passlabel.setText("Password is Incorrect");
                        }

                    }
                }
                if (unamechecker == 0) {
                    passlabel.setText(" ");
                    unamelabel.setText("Username is Does Not Exist");
                }

            } catch (FileNotFoundException ex) {
                java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }

        }
    }
    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            checkerr();//login
        }
    }//GEN-LAST:event_passKeyPressed

    private void unameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameTFActionPerformed

    }//GEN-LAST:event_unameTFActionPerformed

    private void unameTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unameTFKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            checkerr();
        }
    }//GEN-LAST:event_unameTFKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        checkerr();//login codes
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       new register().setVisible(true);
       dispose();       
    }//GEN-LAST:event_jLabel3MouseClicked

    private void icon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MouseClicked
       icon2.setVisible(true);
        icon1.setVisible(false);
        pass.setEchoChar((char)0);
    }//GEN-LAST:event_icon1MouseClicked

    private void icon2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon2MouseClicked
       icon1.setVisible(true);
        icon2.setVisible(false);
        pass.setEchoChar('*');
    }//GEN-LAST:event_icon2MouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
       System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel close;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel passlabel;
    private javax.swing.JTextField unameTF;
    private javax.swing.JLabel unamelabel;
    // End of variables declaration//GEN-END:variables
}
