/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vsystem;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import vsystem.login;

/**
 *
 * @author Raven
 */
public class userDashboard extends javax.swing.JFrame {
public ImageIcon back,iconbg;
    int min = 3, sec = 0, min1, sec1; //setting time
    Timer timer;
    boolean flag = true;
    boolean ifStop = false;

    public userDashboard() {
        initComponents();
        setLocationRelativeTo(null);
        timer();
        try {
            showItem();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(userDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        back = new ImageIcon("src\\icons\\back.jpg");
        iconbg = new ImageIcon("src\\icons\\uic-logolowopac.png");
        jLabel4.setIcon(back);
        logolowo.setIcon(iconbg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        govlabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vpinternallabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        governorcombobox = new javax.swing.JComboBox();
        vginternalcombobox = new javax.swing.JComboBox();
        vpexternallabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        vgexternalcombobox = new javax.swing.JComboBox();
        secretarylabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        secretarycombobox = new javax.swing.JComboBox();
        assistantsecretarylabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        assistantsecretarycombobox = new javax.swing.JComboBox();
        treasurerlabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        treasurercombobox = new javax.swing.JComboBox();
        auditorlabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        auditorcombobox = new javax.swing.JComboBox();
        piolabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        piocombobox = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        logolowo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        minutes = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        seconds = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        govlabel.setBackground(new java.awt.Color(0, 0, 0));
        govlabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        govlabel.setForeground(new java.awt.Color(255, 255, 255));
        govlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        govlabel.setText("Photo");
        govlabel.setAlignmentY(0.0F);
        govlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        govlabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        govlabel.setIconTextGap(0);
        govlabel.setInheritsPopupMenu(false);
        govlabel.setName(""); // NOI18N
        govlabel.setRequestFocusEnabled(false);
        govlabel.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(govlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 39, 143, 142));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Governor");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 17, 143, -1));

        vpinternallabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        vpinternallabel.setForeground(new java.awt.Color(255, 255, 255));
        vpinternallabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vpinternallabel.setText("Photo");
        vpinternallabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(vpinternallabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 39, 144, 142));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Vice-Governor Internal");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 17, 144, -1));

        governorcombobox.setBackground(new java.awt.Color(36, 47, 65));
        governorcombobox.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        governorcombobox.setForeground(new java.awt.Color(255, 255, 255));
        governorcombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        governorcombobox.setBorder(null);
        governorcombobox.setFocusable(false);
        governorcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                governorcomboboxActionPerformed(evt);
            }
        });
        jPanel1.add(governorcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 193, 143, -1));

        vginternalcombobox.setBackground(new java.awt.Color(36, 47, 65));
        vginternalcombobox.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        vginternalcombobox.setForeground(new java.awt.Color(255, 255, 255));
        vginternalcombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        vginternalcombobox.setBorder(null);
        vginternalcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vginternalcomboboxActionPerformed(evt);
            }
        });
        jPanel1.add(vginternalcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 193, 144, -1));

        vpexternallabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        vpexternallabel.setForeground(new java.awt.Color(255, 255, 255));
        vpexternallabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vpexternallabel.setText("Photo");
        vpexternallabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(vpexternallabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 39, 143, 142));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Vice-Governor External");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 17, 143, -1));

        vgexternalcombobox.setBackground(new java.awt.Color(36, 47, 65));
        vgexternalcombobox.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        vgexternalcombobox.setForeground(new java.awt.Color(255, 255, 255));
        vgexternalcombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        vgexternalcombobox.setBorder(null);
        vgexternalcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vgexternalcomboboxActionPerformed(evt);
            }
        });
        jPanel1.add(vgexternalcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 193, 143, -1));

        secretarylabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        secretarylabel.setForeground(new java.awt.Color(255, 255, 255));
        secretarylabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secretarylabel.setText("Photo");
        secretarylabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        secretarylabel.setMaximumSize(new java.awt.Dimension(41, 18));
        secretarylabel.setMinimumSize(new java.awt.Dimension(41, 18));
        secretarylabel.setPreferredSize(new java.awt.Dimension(41, 18));
        jPanel1.add(secretarylabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 39, 147, 142));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Secretary");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 17, 147, -1));

        secretarycombobox.setBackground(new java.awt.Color(36, 47, 65));
        secretarycombobox.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        secretarycombobox.setForeground(new java.awt.Color(255, 255, 255));
        secretarycombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        secretarycombobox.setBorder(null);
        secretarycombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secretarycomboboxActionPerformed(evt);
            }
        });
        jPanel1.add(secretarycombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 193, 147, -1));

        assistantsecretarylabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        assistantsecretarylabel.setForeground(new java.awt.Color(255, 255, 255));
        assistantsecretarylabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        assistantsecretarylabel.setText("Photo");
        assistantsecretarylabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(assistantsecretarylabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 285, 143, 142));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Assistant Secretary");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 251, 143, -1));

        assistantsecretarycombobox.setBackground(new java.awt.Color(36, 47, 65));
        assistantsecretarycombobox.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        assistantsecretarycombobox.setForeground(new java.awt.Color(255, 255, 255));
        assistantsecretarycombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        assistantsecretarycombobox.setBorder(null);
        assistantsecretarycombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assistantsecretarycomboboxActionPerformed(evt);
            }
        });
        jPanel1.add(assistantsecretarycombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 439, 143, -1));

        treasurerlabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        treasurerlabel.setForeground(new java.awt.Color(255, 255, 255));
        treasurerlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        treasurerlabel.setText("Photo");
        treasurerlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(treasurerlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 285, 144, 142));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Treasurer");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 251, 144, -1));

        treasurercombobox.setBackground(new java.awt.Color(36, 47, 65));
        treasurercombobox.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        treasurercombobox.setForeground(new java.awt.Color(255, 255, 255));
        treasurercombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        treasurercombobox.setBorder(null);
        treasurercombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treasurercomboboxActionPerformed(evt);
            }
        });
        jPanel1.add(treasurercombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 439, 144, -1));

        auditorlabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        auditorlabel.setForeground(new java.awt.Color(255, 255, 255));
        auditorlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        auditorlabel.setText("Photo");
        auditorlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(auditorlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 285, 143, 142));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Auditor");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 251, 143, -1));

        auditorcombobox.setBackground(new java.awt.Color(36, 47, 65));
        auditorcombobox.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        auditorcombobox.setForeground(new java.awt.Color(255, 255, 255));
        auditorcombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        auditorcombobox.setBorder(null);
        auditorcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auditorcomboboxActionPerformed(evt);
            }
        });
        jPanel1.add(auditorcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 439, 143, -1));

        piolabel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        piolabel.setForeground(new java.awt.Color(255, 255, 255));
        piolabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        piolabel.setText("Photo");
        piolabel.setToolTipText("");
        piolabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(piolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 285, 147, 142));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Public Information Officer");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 251, -1, -1));

        piocombobox.setBackground(new java.awt.Color(36, 47, 65));
        piocombobox.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        piocombobox.setForeground(new java.awt.Color(255, 255, 255));
        piocombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        piocombobox.setBorder(null);
        piocombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piocomboboxActionPerformed(evt);
            }
        });
        jPanel1.add(piocombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 439, 147, -1));

        jButton2.setBackground(new java.awt.Color(36, 47, 65));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Vote");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 507, 147, 45));
        jPanel1.add(logolowo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 360, 410));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 507, -1, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -10, 850, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 800, 590));

        jPanel2.setBackground(new java.awt.Color(23, 35, 51));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VOTE");

        minutes.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        minutes.setForeground(new java.awt.Color(255, 255, 255));
        minutes.setText("00");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(":");

        seconds.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        seconds.setForeground(new java.awt.Color(255, 255, 255));
        seconds.setText("00");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Timer");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 495, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(minutes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seconds)
                .addGap(87, 87, 87))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seconds)
                            .addComponent(minutes)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(21, 21, 21))))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void governorcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_governorcomboboxActionPerformed
        // TODO add your handling code here:
        call(governorcombobox, govlabel);
    }//GEN-LAST:event_governorcomboboxActionPerformed

    private void vginternalcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vginternalcomboboxActionPerformed
        // TODO add your handling code here:
        call(vginternalcombobox, vpinternallabel);
    }//GEN-LAST:event_vginternalcomboboxActionPerformed

    private void vgexternalcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vgexternalcomboboxActionPerformed
        // TODO add your handling code here:
        call(vgexternalcombobox, vpexternallabel);
    }//GEN-LAST:event_vgexternalcomboboxActionPerformed

    private void secretarycomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secretarycomboboxActionPerformed
        // TODO add your handling code here:
        call(secretarycombobox, secretarylabel);
    }//GEN-LAST:event_secretarycomboboxActionPerformed

    private void treasurercomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treasurercomboboxActionPerformed
        // TODO add your handling code here:
        call(treasurercombobox, treasurerlabel);
    }//GEN-LAST:event_treasurercomboboxActionPerformed

    private void auditorcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auditorcomboboxActionPerformed
        // TODO add your handling code here:
        call(auditorcombobox, auditorlabel);
    }//GEN-LAST:event_auditorcomboboxActionPerformed

    private void piocomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piocomboboxActionPerformed
        // TODO add your handling code here:
        call(piocombobox, piolabel);
    }//GEN-LAST:event_piocomboboxActionPerformed

    public void checkuservoted() throws FileNotFoundException, IOException {
        String line2, content = "";
        String userzz = login.id;
        Scanner sc1 = new Scanner(new FileReader("src\\textFile\\users"));//reading text file
        while (sc1.hasNextLine()) { //logic
            line2 = sc1.nextLine();
            if (line2.equals("")) {
                continue;
            }
            Scanner lineinput2 = new Scanner(line2);
            String iddd = lineinput2.next();
            String firstnameuser = lineinput2.next();
            String surnameuser = lineinput2.next();
            String usercourse = lineinput2.next();
            String gender = lineinput2.next();
            String valid = lineinput2.next();
            String k = firstnameuser + " " + surnameuser;
            if (userzz.equals(k)) {
                if (valid.equals("NOTYETVOTED")) {
                    valid = "VOTED";
                }
                line2 = iddd + " " + firstnameuser + " " + surnameuser + " " + usercourse + " " + gender + " " + valid;
            }
            content = content + line2 + "\n";
        }
        save(content, "src\\textFile\\users");
    }

    public void save(String a, String path) throws IOException {

        BufferedWriter br;
        br = new BufferedWriter(new FileWriter(path));
        br.append(a + "\n");
        br.close();

    }

    public void showItem() throws FileNotFoundException {
        Scanner inp = new Scanner(System.in);
        Scanner sf = null;
        String firstnameusertf = "";
        String surnameusertf = "";
        String user2 = login.id;
        Scanner usertextfield = new Scanner(user2);
        while (usertextfield.hasNext()) {
            firstnameusertf = usertextfield.next();
            surnameusertf = usertextfield.next();
        }

        String course2 = login.linezz;;
        String firstname = "", surname = "", gender = "", department = "", position = "";
        try {
            inp = new Scanner(new FileReader("src\\textFile\\candidates"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(userDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            sf = new Scanner(new FileReader("src\\textFile\\users"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(userDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        while (sf.hasNextLine()) {
            String user3 = sf.nextLine();
            if (user3.equals("")) {
                continue;
            }
            Scanner userline = new Scanner(user3);
            String iddd = userline.next();
            String firstnameuser = userline.next();
            String surnameuser = userline.next();
            String usercourse = userline.next();
            if (firstnameuser.equals(firstnameusertf) && usercourse.equals(course2) && surnameusertf.equals(surnameuser)) {
                while (inp.hasNextLine()) {
                    String fetched = inp.nextLine();
                    if (fetched.equals("")) {
                        continue;
                    }
                    Scanner fetchedd = new Scanner(fetched);
                    firstname = fetchedd.next();
                    surname = fetchedd.next();
                    gender = fetchedd.next();
                    department = fetchedd.next();
                    position = fetchedd.next();
                    if (department.equals(usercourse)) {
                        if (position.equals("GOVERNOR")) {
                            governorcombobox.addItem(firstname + " " + surname);
                        }
                        if (position.equals("VG-INTERNAL")) {
                            vginternalcombobox.addItem(firstname + " " + surname);
                        }
                        if (position.equals("VG-EXTERNAL")) {
                            vgexternalcombobox.addItem(firstname + " " + surname);
                        }
                        if (position.equals("SECRETARY")) {
                            secretarycombobox.addItem(firstname + " " + surname);
                        }
                        if (position.equals("ASSISTANT-SECRETARY")) {
                            assistantsecretarycombobox.addItem(firstname + " " + surname);
                        }
                        if (position.equals("TREASURER")) {
                            treasurercombobox.addItem(firstname + " " + surname);
                        }
                        if (position.equals("AUDITOR")) {
                            auditorcombobox.addItem(firstname + " " + surname);
                        }
                        if (position.equals("PIO")) {
                            piocombobox.addItem(firstname + " " + surname);
                        }
                    }
                }
            }
        }

        inp.close();
    }

    public void sum() { //viewing summaryvote

        Votesummary m = new Votesummary();
        m.setVisible(true);

        String pos1="", pos2="", pos3="", pos4="", pos5="", pos6="", pos7="", pos8="";
        pos1 = governorcombobox.getSelectedItem().toString();
        pos2 = vginternalcombobox.getSelectedItem().toString();
        pos3 = vgexternalcombobox.getSelectedItem().toString();
        pos4 = secretarycombobox.getSelectedItem().toString();
        pos5 = assistantsecretarycombobox.getSelectedItem().toString();
        pos6 = treasurercombobox.getSelectedItem().toString();
        pos7 = auditorcombobox.getSelectedItem().toString();
        pos8 = piocombobox.getSelectedItem().toString();

        if (pos1.equals("Select")) {        
            pos1="N/A";
        }
        if (pos2.equals("Select")) {
        
          pos2="N/A";
        }
        if (pos3.equals("Select")) {
         
           pos3="N/A";
        }
        if (pos4.equals("Select")) {
          
           pos4="N/A";
        }
        if (pos5.equals("Select")) {
        
           pos5="N/A";
        }
        if (pos6.equals("Select")) {
         
          pos6="N/A";
        }
        if (pos7.equals("Select")) {
        
           pos7="N/A";
        }
        if (pos8.equals("Select")) {
        
            pos8="N/A";
        } 
            Votesummary.poss1.setText(pos1);
            Votesummary.poss2.setText(pos2);
            Votesummary.poss3.setText(pos3);
            Votesummary.poss4.setText(pos4);
            Votesummary.poss5.setText(pos5);
            Votesummary.poss6.setText(pos6);
            Votesummary.poss7.setText(pos7);
            Votesummary.poss8.setText(pos8);
        

        try {
            checkuservoted();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(userDashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(userDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }

    public void timer() { //timercodes
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                userDashboard.minutes.setForeground(Color.WHITE);
                userDashboard.seconds.setForeground(Color.WHITE);
                if (ifStop) {
                    min = min1;
                    sec = sec1;
                    ifStop = false;
                }
                if (min == 0) {

                    minutes.setForeground(Color.RED);
                    seconds.setForeground(Color.RED);
                }

                if (sec == 0) {
                    sec = 60;
                    min--;
                }
                if (min < 0) {
                    setVisible(false);
                    Object[] options = {"Ok"};
                    int yesorno = JOptionPane.showOptionDialog(null, "Times Up!", "Stopped",
                            JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,
                            null, options, options[0]);//here force unable to vote
                    if (yesorno == 0) {
                        sum();//yes optionx`
                        try {
                            checkuservoted();
                        } catch (FileNotFoundException ex) {
                            Logger.getLogger(userDashboard.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(userDashboard.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }

                    min = 0;
                    sec = 0;
                    timer.stop();
                } else {
                    sec--;
                    if (sec <= 9) {
                        seconds.setText("0" + sec);
                        flag = false;
                    }
                    if (min <=9) {
                        minutes.setText("0" + min);
                        if (sec <=9) {
                            seconds.setText("0" + sec);
                        } else {
                            seconds.setText("" + sec);
                        }
                        flag = false;

                    }
                    if (flag) {
                        minutes.setText("" + min);
                        seconds.setText("" + sec);
                    }
                }
            }
        });
        timer.start();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        timer.stop(); //automatic stop when pressed
        sum();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void assistantsecretarycomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assistantsecretarycomboboxActionPerformed
        // TODO add your handling code here:
        call(assistantsecretarycombobox, assistantsecretarylabel);
    }//GEN-LAST:event_assistantsecretarycomboboxActionPerformed
    private void call(JComboBox combobox, JLabel label) {
        Scanner inp = null, sd, sf = null;
        combobox.removeItem("Select");
        label.setPreferredSize(new Dimension(35, 16));
        label.setMinimumSize(new Dimension(35, 16));
        label.setMaximumSize(new Dimension(35, 16));
        label.setText("");
        String fullname, firstname = null, surname = null, firstname2, surname2;
        String image = "", images = "";
        try {
            inp = new Scanner(new FileReader("src\\textFile\\imagepaths"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(userDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            sd = new Scanner(new FileReader("src\\textFile\\candidates"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(userDashboard.class.getName()).log(Level.SEVERE, null, ex);
        }

        fullname = (String) combobox.getSelectedItem();
        Scanner sc = new Scanner(fullname);
        while (sc.hasNextLine()) {
            firstname = sc.next();
            surname = sc.next();
        }

        while (inp.hasNextLine()) {
            String fetched = inp.nextLine();
            if (fetched.equals("")) {
                continue;
            }
            Scanner fetchedd = new Scanner(fetched);
            firstname2 = fetchedd.next();
            surname2 = fetchedd.next();

            if (firstname.equals(firstname2) && surname.equals(surname2)) {
                image = fetchedd.next();
                while (fetchedd.hasNext()) {
                    image = image + " " + fetchedd.next();
                }
                ImageIcon imIco = new ImageIcon(image);
                Image imFit = imIco.getImage();

                Image imgFit = imFit.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);

                label.setIcon(new ImageIcon(imgFit));

                images = image;

            }

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox assistantsecretarycombobox;
    private javax.swing.JLabel assistantsecretarylabel;
    public static javax.swing.JComboBox auditorcombobox;
    private javax.swing.JLabel auditorlabel;
    public static javax.swing.JComboBox governorcombobox;
    private javax.swing.JLabel govlabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logolowo;
    public static javax.swing.JLabel minutes;
    public static javax.swing.JComboBox piocombobox;
    private javax.swing.JLabel piolabel;
    public static javax.swing.JLabel seconds;
    public static javax.swing.JComboBox secretarycombobox;
    private javax.swing.JLabel secretarylabel;
    public static javax.swing.JComboBox treasurercombobox;
    private javax.swing.JLabel treasurerlabel;
    public static javax.swing.JComboBox vgexternalcombobox;
    public static javax.swing.JComboBox vginternalcombobox;
    private javax.swing.JLabel vpexternallabel;
    private javax.swing.JLabel vpinternallabel;
    // End of variables declaration//GEN-END:variables

}
