/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vsystem;

import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Raven
 */
public class verifierDashboard extends javax.swing.JFrame {

    public ImageIcon back;
    public verifierDashboard() {
        initComponents();
        deactivate.setVisible(false);
        setLocationRelativeTo(null);
     back = new ImageIcon("src\\icons\\back.jpg");
     backg.setIcon(back);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        unameTF = new javax.swing.JTextField();
        verifyyy = new javax.swing.JButton();
        deactivate = new javax.swing.JButton();
        tog = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        verifyyy1 = new javax.swing.JButton();
        backg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MODE:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 24));

        unameTF.setBackground(new java.awt.Color(36, 47, 65));
        unameTF.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        unameTF.setForeground(new java.awt.Color(255, 255, 255));
        unameTF.setBorder(null);
        unameTF.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(unameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 230, 30));

        verifyyy.setBackground(new java.awt.Color(36, 47, 65));
        verifyyy.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        verifyyy.setForeground(new java.awt.Color(255, 255, 255));
        verifyyy.setText("Verify");
        verifyyy.setBorder(null);
        verifyyy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyyyActionPerformed(evt);
            }
        });
        jPanel1.add(verifyyy, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 100, 35));

        deactivate.setBackground(new java.awt.Color(36, 47, 65));
        deactivate.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        deactivate.setForeground(new java.awt.Color(255, 255, 255));
        deactivate.setText("Deactivate");
        deactivate.setBorder(null);
        deactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deactivateActionPerformed(evt);
            }
        });
        jPanel1.add(deactivate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 100, 35));

        tog.setBackground(new java.awt.Color(36, 47, 65));
        tog.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tog.setForeground(new java.awt.Color(255, 255, 255));
        tog.setText("Verify");
        tog.setBorder(null);
        tog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togActionPerformed(evt);
            }
        });
        jPanel1.add(tog, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 90, 35));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID#:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, 30));

        jPanel2.setBackground(new java.awt.Color(23, 35, 51));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VERIFY VOTEES");

        verifyyy1.setBackground(new java.awt.Color(36, 47, 65));
        verifyyy1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        verifyyy1.setForeground(new java.awt.Color(255, 255, 255));
        verifyyy1.setText("Back");
        verifyyy1.setBorder(null);
        verifyyy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyyy1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(verifyyy1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verifyyy1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 80));

        backg.setText("jLabel4");
        jPanel1.add(backg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 430, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verifyyyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyyyActionPerformed
        veri();
    }//GEN-LAST:event_verifyyyActionPerformed

    private void deactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deactivateActionPerformed
       deact();
    }//GEN-LAST:event_deactivateActionPerformed

    private void togActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togActionPerformed
      if (tog.isSelected()){
          deactivate.setVisible(true);
          verifyyy.setVisible(false);
          tog.setText("Deactivate");
      }else{
          deactivate.setVisible(false); 
           verifyyy.setVisible(true);
          tog.setText("Verify");
          
      }
    }//GEN-LAST:event_togActionPerformed

    private void verifyyy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyyy1ActionPerformed
        dispose();
        new adminDashboard().setVisible(true);
    }//GEN-LAST:event_verifyyy1ActionPerformed
   
    public void veri(){
        String uname,stat,line = null,username,password,status,content="";
              int unamechecker=0;
              uname=unameTF.getText();
             
              try{
                  Scanner sc = new Scanner (new FileReader("src\\textFile\\logintxt"));
                while(sc.hasNextLine()){
                line = sc.nextLine();
                 if(line.equals("")){
            continue;
        }
        Scanner lineinput= new Scanner (line);
        username=lineinput.next();
         password=lineinput.next();
         stat=lineinput.next();
         status=lineinput.next();
          
          if(uname.equals(username)){
               unamechecker=1;
                  if(status.equals("Verified")){
                      status="Verified";
                      line= username+"\t"+password+"\t"+stat+"\t"+status;
                        JOptionPane.showMessageDialog(null, "Account Already Verified.");
                  }
                  if(status.equals("NotVerified")){
                      status="Verified";
                     line= username+"\t"+password+"\t"+stat+"\t"+status;
                        JOptionPane.showMessageDialog(null, "Account Verified.");
                       }

                    
                   } 
            content=content+line+"\n";
                                        }
                
                if(unamechecker==0){
                    JOptionPane.showMessageDialog(null, "Username Does not Exist");
                }
               savez(content,"src\\textFile\\logintxt") ;
     
                   }            
              catch (FileNotFoundException ex) {
                 Logger.getLogger(verifierDashboard.class.getName()).log(Level.SEVERE, null, ex);
             } catch (IOException ex) {
               Logger.getLogger(verifierDashboard.class.getName()).log(Level.SEVERE, null, ex);
           }
    }
    public void deact(){
        String uname,stat,line = null,username,password,status,content="";
              int unamechecker=0;
              uname=unameTF.getText();
             
              try{
                  Scanner sc = new Scanner (new FileReader("src\\textFile\\logintxt"));
                while(sc.hasNextLine()){
                line = sc.nextLine();
                 if(line.equals("")){
            continue;
        }
        Scanner lineinput= new Scanner (line);
        username=lineinput.next();
         password=lineinput.next();
         stat=lineinput.next();
         status=lineinput.next();
          
          if(uname.equals(username)){
               unamechecker=1;
                if(status.equals("NotVerified")){
                     status="NotVerified";
                       line= username+"\t"+password+"\t"+stat+"\t"+status;
                        JOptionPane.showMessageDialog(null, "Account Already Deactivated.");
                  }
                  if(status.equals("Verified")){
                      status="NotVerified";
                     line= username+"\t"+password+"\t"+stat+"\t"+status;
                        JOptionPane.showMessageDialog(null, "Account Deactivated.");
                       }
                   
                   } 
            content=content+line+"\n";
                                        }
                
                if(unamechecker==0){
                    JOptionPane.showMessageDialog(null, "Username Does not Exist");
                }
               savez(content,"src\\textFile\\logintxt") ;
     
                   }            
              catch (FileNotFoundException ex) {
                 Logger.getLogger(verifierDashboard.class.getName()).log(Level.SEVERE, null, ex);
             } catch (IOException ex) {
               Logger.getLogger(verifierDashboard.class.getName()).log(Level.SEVERE, null, ex);
           }
    }
    public  void savez(String a, String path) throws IOException {
        
    BufferedWriter br;
        br = new BufferedWriter(new FileWriter(path));
        br.append(a+"\n");
        br.close(); 
        //setVisible(false);
        //dispose();
        //Usermanagement x= new Usermanagement();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(verifierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(verifierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(verifierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(verifierDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new verifierDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backg;
    private javax.swing.JButton deactivate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton tog;
    private javax.swing.JTextField unameTF;
    private javax.swing.JButton verifyyy;
    private javax.swing.JButton verifyyy1;
    // End of variables declaration//GEN-END:variables
}
