/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vsystem;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import vsystem.adminDashboard;
import static vsystem.adminDashboard.btn_1;
import static vsystem.adminDashboard.btn_12;
import static vsystem.adminDashboard.btn_3;
import static vsystem.adminDashboard.btn_4;
import static vsystem.adminDashboard.btn_8;
import static vsystem.adminDashboard.btn_9;
import static vsystem.adminDashboard.ind_1;
import static vsystem.adminDashboard.ind_12;
import static vsystem.adminDashboard.ind_3;
import static vsystem.adminDashboard.ind_4;
import static vsystem.adminDashboard.ind_8;
import static vsystem.adminDashboard.ind_9;
import static vsystem.adminDashboard.resetColor;
import static vsystem.adminDashboard.setColor;
/**
 *
 * @author Raven
 */
public class voteResult extends javax.swing.JFrame {

     public ImageIcon back;
    public voteResult() {
        initComponents();
        setLocationRelativeTo(null);
         back = new ImageIcon("src\\icons\\back.jpg");
     backg.setIcon(back);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        poss1 = new javax.swing.JLabel();
        poss2 = new javax.swing.JLabel();
        poss3 = new javax.swing.JLabel();
        poss8 = new javax.swing.JLabel();
        poss7 = new javax.swing.JLabel();
        poss6 = new javax.swing.JLabel();
        poss5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        poss4 = new javax.swing.JLabel();
        v1 = new javax.swing.JLabel();
        v2 = new javax.swing.JLabel();
        v3 = new javax.swing.JLabel();
        v4 = new javax.swing.JLabel();
        v5 = new javax.swing.JLabel();
        v6 = new javax.swing.JLabel();
        v7 = new javax.swing.JLabel();
        v8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        departmentz = new javax.swing.JLabel();
        backg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Governor:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Vice-Governor(INTERNAL):");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vice-Governor(EXTERNAL):");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Secretary:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pio:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Auditor:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Treasurer:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Assistant Secretary:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        poss1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        poss1.setForeground(new java.awt.Color(255, 255, 255));
        poss1.setText("N/A");
        jPanel1.add(poss1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        poss2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        poss2.setForeground(new java.awt.Color(255, 255, 255));
        poss2.setText("N/A");
        jPanel1.add(poss2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        poss3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        poss3.setForeground(new java.awt.Color(255, 255, 255));
        poss3.setText("N/A");
        jPanel1.add(poss3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        poss8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        poss8.setForeground(new java.awt.Color(255, 255, 255));
        poss8.setText("N/A");
        jPanel1.add(poss8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        poss7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        poss7.setForeground(new java.awt.Color(255, 255, 255));
        poss7.setText("N/A");
        jPanel1.add(poss7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        poss6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        poss6.setForeground(new java.awt.Color(255, 255, 255));
        poss6.setText("N/A");
        jPanel1.add(poss6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        poss5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        poss5.setForeground(new java.awt.Color(255, 255, 255));
        poss5.setText("N/A");
        jPanel1.add(poss5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Name");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        poss4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        poss4.setForeground(new java.awt.Color(255, 255, 255));
        poss4.setText("N/A");
        jPanel1.add(poss4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        v1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        v1.setForeground(new java.awt.Color(255, 255, 255));
        v1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(v1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 80, 20));

        v2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        v2.setForeground(new java.awt.Color(255, 255, 255));
        v2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        v2.setText("          ");
        jPanel1.add(v2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 80, 20));

        v3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        v3.setForeground(new java.awt.Color(255, 255, 255));
        v3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        v3.setText("                  ");
        jPanel1.add(v3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 80, 20));

        v4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        v4.setForeground(new java.awt.Color(255, 255, 255));
        v4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        v4.setText("             ");
        jPanel1.add(v4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 80, 20));

        v5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        v5.setForeground(new java.awt.Color(255, 255, 255));
        v5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        v5.setText("                 ");
        jPanel1.add(v5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 80, 20));

        v6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        v6.setForeground(new java.awt.Color(255, 255, 255));
        v6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        v6.setText("               ");
        jPanel1.add(v6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 80, 20));

        v7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        v7.setForeground(new java.awt.Color(255, 255, 255));
        v7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        v7.setText("              ");
        jPanel1.add(v7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 80, 20));

        v8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        v8.setForeground(new java.awt.Color(255, 255, 255));
        v8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        v8.setText("              ");
        jPanel1.add(v8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 80, 20));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("No. of Votes");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jButton1.setBackground(new java.awt.Color(36, 47, 65));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Close");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 120, 40));

        departmentz.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        departmentz.setForeground(new java.awt.Color(255, 255, 255));
        departmentz.setText("DEPARTMENT");
        jPanel1.add(departmentz, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 340, 31));
        jPanel1.add(backg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, -880, 690, 1440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        new adminDashboard().setVisible(true);
       adminDashboard. change.setText("VIEW VOTES");
        adminDashboard. cd5.setVisible(true);
        adminDashboard. cd2.setVisible(false);
        adminDashboard. cd3.setVisible(false);
        adminDashboard. cd4.setVisible(false);
        adminDashboard. cd1.setVisible(false);
        adminDashboard. cd6.setVisible(false);    
        adminDashboard.tabp1.setSelectedIndex(8);
           adminDashboard. setColor(adminDashboard.btn_8);
        adminDashboard.ind_8.setOpaque(true);
        adminDashboard.resetColor(new JPanel[]{btn_3, btn_1,  btn_12,btn_9,btn_4}, new JPanel[]{ind_3, ind_1,  ind_12,ind_9,ind_4});
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(voteResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(voteResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(voteResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(voteResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new voteResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backg;
    public static javax.swing.JLabel departmentz;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel poss1;
    public static javax.swing.JLabel poss2;
    public static javax.swing.JLabel poss3;
    public static javax.swing.JLabel poss4;
    public static javax.swing.JLabel poss5;
    public static javax.swing.JLabel poss6;
    public static javax.swing.JLabel poss7;
    public static javax.swing.JLabel poss8;
    public static javax.swing.JLabel v1;
    public static javax.swing.JLabel v2;
    public static javax.swing.JLabel v3;
    public static javax.swing.JLabel v4;
    protected static javax.swing.JLabel v5;
    public static javax.swing.JLabel v6;
    public static javax.swing.JLabel v7;
    public static javax.swing.JLabel v8;
    // End of variables declaration//GEN-END:variables
}
